並列処理ハンズオンの追加
iij/bootcamp pull request #106
Opened 2022-08-14 03:55 UTC by ryoya-fujimoto

2022-08-15 01:55 UTC, satosi-k commented on src/server-app/concurrent/README.md
> +pythonで書かれたコードは最終的にアセンブラにコンパイルされて実行されます。`dis`を利用して実際に実行されるアセンブラを見てみましょう。
CPython の場合、実行時に変換されるのはアセンブリではなくバイトコードかと思います。
後続の dis モジュールが扱っているのも CPython VM 向けのバイトコードです。
(この点は実装依存なので、あくまで「CPython では」となります)

2022-08-15 01:56 UTC, satosi-k commented on src/server-app/concurrent/README.md
> +vscode等を利用して作業用ディレクトリ(`bootcamp_work`)でpythonコードを書いていきましょう。
「Python」と「python」で表記が揺れているようです。
公式には先頭が大文字の「Python」が正しいかと思います。

2022-08-15 01:58 UTC, satosi-k commented on src/server-app/concurrent/Dockerfile
> +FROM golang:latest
プログラミング言語に Python を使うのであれば、Python のオフィシャルイメージを使うのはどうでしょうか。

https://hub.docker.com/_/python

2022-08-15 02:03 UTC, satosi-k commented on src/server-app/concurrent/README.md
> +このプログラムではユーザからのリクエストを同時に処理するために [ThreadingHTTPServer](https://docs.python.org/ja/3.7/library/http.server.html#http.server.ThreadingHTTPServer) を利用しています。
ドキュメントのリンク先が Python 3.7 向けになっているので、ハンズオンで利用しているバージョン (3.9) とズレているようです。
揃えるか、あるいは最新の安定バージョン向けにするのが良いように思いました。

https://docs.python.org/ja/3.9/library/http.server.html#http.server.ThreadingHTTPServer
https://docs.python.org/ja/3/library/http.server.html#http.server.ThreadingHTTPServer

2022-08-15 02:21 UTC, satosi-k commented on src/server-app/concurrent/README.md
> +つまりthread1が1を実行した後、同時にthread2が1を実行する可能性があります。つまりPythonにおける`a += 1`はレースコンディションを起こす可能性があり、「スレッドセーフではない」ことが分かります。
「もしかすると補足があった方が良いかもしれない」程度の内容ですが、CPython には GIL (Global Interpreter Lock) があるため、複数のスレッドが真に同時には実行されません (= 並行処理)。

2022-08-15 02:27 UTC, satosi-k commented on src/server-app/concurrent/README.md
> +例: c言語の`__sync_fetch_and_add`など
かなり重箱の隅をつつくような指摘ですが、この例は「プログラミング言語が規定している仕様」でしょうか？
「たまたま( コンパイラなどの?) 実装がそうなっている」のかどうかとは区別した方が良いように思います。

2022-08-15 02:30 UTC, satosi-k commented on src/server-app/concurrent/README.md
> +- スレッドプログラミング（並列処理）を書いているという認識を持ち、書こうとしている処理がスレッドセーフなのか常に確認しましょう
先述したように GIL 相当の実装によってスレッドプログラミングが並行処理になる場合もあるため、括弧書きとして並列処理を併記するのは厳密には正しくないかもしれません。

2022-08-15 02:31 UTC, satosi-k commented on src/server-app/concurrent/README.md
> +  - フレームワーク側で推奨されている
この行は途中で記述が切れていそうです。

2022-08-15 02:31 UTC, satosi-k commented on src/server-app/concurrent/README.md
> +- ロックなど並列処理の実装を行う際は自前で実装せず、必ずライブラリを利用しましょう
ここはs/並列処理/排他制御/でしょうか？

2022-08-15 05:46 UTC, ryoya-fujimoto commented on src/server-app/concurrent/Dockerfile
> +FROM golang:latest
ほんとですね。なんでgolangなんだ・・・

2022-08-15 06:46 UTC, ryoya-fujimoto commented
@satosi-k さん
ありがとうございます。一通り修正しました。
特にGILについての記述が正しいかご確認いただきたく

2022-08-15 06:54 UTC, igrep commented on src/server-app/concurrent/README.md
> +そのため少なくともCPython上では`a += 1`のような処理を書いてもレースコンディションは実質発生しません。
ここでいう「真に同時に実行」は複数のOSのスレッド（CPUのコア）で実行される、という意味なのでレースコンディションが発生しないなんてことはないです。（現に挙げていたサンプルでは競合してますし）
参考: https://docs.python.org/ja/3/faq/library.html#can-t-we-get-rid-of-the-global-interpreter-lock

2022-08-15 07:04 UTC, ryoya-fujimoto commented on src/server-app/concurrent/README.md
> +そのため少なくともCPython上では`a += 1`のような処理を書いてもレースコンディションは実質発生しません。
なるほど。書き方難しいですね。
複数のCPUコアで並列実行されないとしてもこのサンプルの動作的に影響はないので、GILの補足はなくても良さそうですが、どうでしょうか。

2022-08-15 07:08 UTC, igrep commented on src/server-app/concurrent/README.md
> +そのため少なくともCPython上では`a += 1`のような処理を書いてもレースコンディションは実質発生しません。
> GILの補足はなくても良さそうですが、どうでしょうか。

私もそう思います。元のコメントを見たときパッと詳細を思い出せなかったのでその場で指摘できず済みませんでした。

2022-08-16 00:56 UTC, satosi-k commented on src/server-app/concurrent/README.md
> +そのため少なくともCPython上では`a += 1`のような処理を書いてもレースコンディションは実質発生しません。
言葉足らずですみません。
@igrep さんが指摘されている通り「真に同時に実行」というのは、複数の異なるカーネルスレッドから同じタイミングで処理が実行される余地があるかを示していました。
また、GIL があるからといってレースコンディションが起こらないということはないです。

```
1. 「a」というメモリ領域から値を読み込む(`LOAD_NAME`)
2. 加算する(`INPLACE_ADD`)
3. 「a」というメモリ領域に値を書き込む(`STORE_NAME`)

つまりthread1が1を実行した後、同時にthread2が1を実行する可能性があります。つまりPythonにおける`a += 1`はレースコンディションを起こす可能性があり、「スレッドセーフではない」ことが分かります。
```

上記でいうと thread1 が 1 を実行した後にコンテキストスイッチが生じ、実行が thread2 に移って thread2 が 1 を実行することでレースコンディションが生じます。

2022-08-16 01:00 UTC, satosi-k commented on src/server-app/concurrent/README.md
> +そのため少なくともCPython上では`a += 1`のような処理を書いてもレースコンディションは実質発生しません。
私も GIL 自体の説明はなくても良いと思います。

> つまりthread1が1を実行した後、同時にthread2が1を実行する可能性があります。

代わりに、この部分をコンテキストスイッチを用いた説明に修正するのはどうでしょうか。

2022-08-16 01:43 UTC, satosi-k commented on src/server-app/concurrent/README.md
> +title: 並列処理ハンズオン
「平行」と「並列」が場所によって揺れているようです。
「並行・並列」のように併記するか、あるいは「並行」に寄せるのが良いでしょうか？

2022-08-16 01:43 UTC, satosi-k commented on src/server-app/concurrent/README.md
> +### 共有メモリとレースコンディション
共有メモリ (Shared Memory) という用語からは、どちらかというとプロセス間通信等に使う特別な領域をイメージしますが、どうでしょうか。
「メモリの共有」など？

2022-08-16 01:43 UTC, satosi-k commented on src/server-app/concurrent/README.md
> +クリティカルセクションを保護する手法の一つが、ロックを取得する排他制御と呼ばれるものです。まずは素朴に実装してみましょう。
「排他制御」と「排他処理」で表記が揺れているようです。

2022-08-16 01:43 UTC, satosi-k commented on src/server-app/concurrent/README.md
> +1. 最初がリクエスト(thread1)が来て`count_and_do_something`が実行される
typo のようです。
「最初のリクエスト」

2022-08-16 01:43 UTC, satosi-k commented on src/server-app/concurrent/README.md
> +`a += 1`と言うコードは6行のアセンブリに変換されます。内容を見てみると以下のように動作することが分かります。
ここは修正漏れでしょうか。

2022-08-16 01:43 UTC, satosi-k commented on src/server-app/concurrent/README.md
> +`a += 1`と言うコードは6行のアセンブリに変換されます。内容を見てみると以下のように動作することが分かります。
ところで、バイトコードで 1 or n 命令かどうかと、処理がアトミックかどうかは実のところ無関係という点はミスリードを誘うかもしれないですね。
(1 命令ならアトミックなんだな、という勘違いを生む恐れ)
たとえばバイトコードが n 命令だったとしても VM がアトミックな機械語として実行する可能性はありますし、1 命令でもアトミックでない機械語として実行されうるという点は実装依存かと思うので。

2022-08-16 01:46 UTC, ryoya-fujimoto commented on src/server-app/concurrent/README.md
> +そのため少なくともCPython上では`a += 1`のような処理を書いてもレースコンディションは実質発生しません。
「コンテキストスイッチ」に関しては説明があってもいいかと思ったので、GILと絡めてtipsを追加してみました

2022-08-16 01:46 UTC, ryoya-fujimoto commented on src/server-app/concurrent/README.md
> +title: 並列処理ハンズオン
「並行・並列」の方が良さそうですね

2022-08-16 01:47 UTC, ryoya-fujimoto commented on src/server-app/concurrent/README.md
> +### 共有メモリとレースコンディション
「メモリ領域の共有」とかですかね

2022-08-16 01:51 UTC, ryoya-fujimoto commented on src/server-app/concurrent/README.md
> +`a += 1`と言うコードは6行のアセンブリに変換されます。内容を見てみると以下のように動作することが分かります。
あー、難しいですね・・。
本来はPython（コンパイラ？）の言語仕様からthread safeかどうかを確認し、その上でなぜだろう・・という仕組みの説明にバイトコードを使うべきですね。
とはいえ参照すべき仕様はどこかと聞かれると見つけられていません

2022-08-16 01:53 UTC, ryoya-fujimoto commented on src/server-app/concurrent/README.md
> +`a += 1`と言うコードは6行のアセンブリに変換されます。内容を見てみると以下のように動作することが分かります。
「仕様です」と言い切ってしまって、「なぜこんな1行の短いコードなのにアトミックじゃないんでしょう」という切り口で説明するのがいい気がしてきました。

2022-08-16 02:21 UTC, igrep requested changes
「コンテキストスイッチ」の用法について気づいたので指摘致しました 🙏

2022-08-16 02:21 UTC, igrep commented on src/server-app/concurrent/README.md
> +つまりthread1が1を実行した後、たまたまコンテキストスイッチが発生しthread2が1を実行する可能性があります。つまりPythonにおける`a += 1`はレースコンディションを起こす可能性があり、「スレッドセーフではない」ことが分かります。
ここで言う「コンテキストスイッチ」はカーネルのコンテキストスイッチのことではないでしょうから、後で説明する「コンテキストスイッチ」と意味が食い違ってしまいますし、元の通り「同時に」と言い切ってしまっていいと思います。

さっと検索したり自分の記憶を探ったりした限り、普通「コンテキストスイッチ」というと、OSによってスレッドやプロセスを切り替えることを指すようなので、Pythonのスレッドについて使うのは避けた方がいいかと思います。

参考: https://ja.wikipedia.org/wiki/%E3%82%B3%E3%83%B3%E3%83%86%E3%82%AD%E3%82%B9%E3%83%88%E3%82%B9%E3%82%A4%E3%83%83%E3%83%81

2022-08-16 02:21 UTC, igrep commented on src/server-app/concurrent/README.md
> +「並行処理」と言う場合はある時間内に複数タスクを実行できればいいので、コンテキストスイッチによってタスクを切り替えながら処理する動作も含みます。
改めて探して気づきましたが、ここでも「コンテキストスイッチ」という単語を通例とは異なる用法で使っているようです。
こんな言い換えでいかがでしょうか:

```suggestion
「並行処理」と言う場合はある時間内に複数タスクを実行できればいいので、実行するタスクを小まめに切り替えながら処理する動作も含みます。
```

2022-08-16 07:41 UTC, satosi-k commented on src/server-app/concurrent/README.md
> +つまりthread1が1を実行した後、たまたまコンテキストスイッチが発生しthread2が1を実行する可能性があります。つまりPythonにおける`a += 1`はレースコンディションを起こす可能性があり、「スレッドセーフではない」ことが分かります。
> ここで言う「コンテキストスイッチ」はカーネルのコンテキストスイッチのことではないでしょうから

ここの記述は CPython の文脈での説明になっているので、スレッドに 1:1 モデルを採用している CPython のスレッドの切り替わりタイミングはカーネルスレッドのコンテキストスイッチと一致することから、特に間違っているというわけでもないかと思います。
一方で、Python というプログラミング言語の仕様的な観点で見るのであれば、Python スレッドの切り替わりタイミングとカーネルスレッドのコンテキストスイッチのタイミングは一致するとは限らないため、別の言い替えをすることに異議はないです。

(ちなみに私はよりざっくりとプロセスやスレッド (実装の詳細問わず) の切り替えをコンテキストスイッチと認識していました)

2022-08-16 08:11 UTC, igrep commented on src/server-app/concurrent/README.md
> +つまりthread1が1を実行した後、たまたまコンテキストスイッチが発生しthread2が1を実行する可能性があります。つまりPythonにおける`a += 1`はレースコンディションを起こす可能性があり、「スレッドセーフではない」ことが分かります。
> スレッドの実装として 1:1 モデルを採用している CPython のスレッドの切り替わりタイミングはカーネルスレッドのコンテキストスイッチと一致することから、特に間違っているというわけでもないかと思います。

すみません、CPythonの仕様を誤解してました！

2022-08-16 08:44 UTC, ryoya-fujimoto commented on src/server-app/concurrent/README.md
> +つまりthread1が1を実行した後、たまたまコンテキストスイッチが発生しthread2が1を実行する可能性があります。つまりPythonにおける`a += 1`はレースコンディションを起こす可能性があり、「スレッドセーフではない」ことが分かります。
元の記述の方が誤解を招かなそうですね。戻しちゃいます

2022-08-16 09:08 UTC, ryoya-fujimoto commented
@igrep @satosi-k 
指摘点を一通り修正できたと思います。

2022-08-16 09:21 UTC, igrep approved these changes
対応ありがとうございました！LGTMです！
![image](https://user-images.githubusercontent.com/227057/184845060-e87fe244-0484-4fbe-84f5-e6d3036d052a.png)

2022-08-16 09:59 UTC, ryoya-fujimoto commented on src/server-app/concurrent/README.md
> +つまりthread1が1を実行した後、たまたまコンテキストスイッチが発生しthread2が1を実行する可能性があります。つまりPythonにおける`a += 1`はレースコンディションを起こす可能性があり、「スレッドセーフではない」ことが分かります。
言われてみるとそもそも処理の順番が入れ替わる話をしているので、「同時に」というと日本語的にも微妙な気がしますね。

2022-08-16 10:00 UTC, ryoya-fujimoto commented on src/server-app/concurrent/README.md
> +つまりthread1が1を実行した後、たまたまコンテキストスイッチが発生しthread2が1を実行する可能性があります。つまりPythonにおける`a += 1`はレースコンディションを起こす可能性があり、「スレッドセーフではない」ことが分かります。
こんな説明の仕方はどうでしょうか

```
`a += 1`というコードは上記の通り6行のバイトコードに変換されます。内容を見てみると以下のように動作することが分かります。

1. 「a」というメモリ領域から値を読み込む(`LOAD_NAME`)
2. 加算する(`INPLACE_ADD`)
3. 「a」というメモリ領域に値を書き込む(`STORE_NAME`)

つまり`a += 1`という一見1ステップのコードでも、バイトコードやその先の機械語レベルでは複数のステップに分かれた処理である可能性があります。
（ここで「可能性」と言っているのは、あくまで言語やコンパイラの仕様や実装次第なためです。少なくともCPythonではアトミックな機械語は生成されないはずです。）

仮に機械語レベルで複数ステップに分かれた処理であった場合、タイミングによってはthread1が1ステップ目を実行した後、
入れ替わりthread2が1ステップ目を実行する可能性があります。
そのため`a += 1`のようなコードでも、レースコンディションを起こす可能性があります。
```

2022-08-17 07:04 UTC, satosi-k commented on src/server-app/concurrent/README.md
> +つまりthread1が1を実行した後、たまたまコンテキストスイッチが発生しthread2が1を実行する可能性があります。つまりPythonにおける`a += 1`はレースコンディションを起こす可能性があり、「スレッドセーフではない」ことが分かります。
とても良い説明だと思いました！

2022-08-17 07:14 UTC, satosi-k approved these changes

2022-08-17 07:15 UTC, satosi-k commented
ご対応いただきありがとうございました！

2022-08-18 02:01 UTC, ryoya-fujimoto commented
レビューありがとうございました。マージしちゃいます

2022-08-18 02:02 UTC, merged