2023 FastAPI の作成 第1版
iij/bootcamp pull request #129
Opened 2023-07-11 01:54 UTC by ainamori

2023-07-12 07:51 UTC, igrep requested changes
取り急ぎtypoの報告を。

2023-07-12 07:51 UTC, igrep commented on src/server-app/fastapi/README.md
> +FastAPIはPythonのWebフレームワークですが、Pythonコアパッケージに含まれている者ではありません。
Typo: 者 -> もの

```suggestion
FastAPIはPythonのWebフレームワークですが、Pythonコアパッケージに含まれているものではありません。
```

2023-07-13 09:47 UTC, ryoya-fujimoto commented
@ainamori 
ざっと見ですが、特に気になる点はありませんでした。
上記typoの対応+ Approve後にマージしてしまってください

2023-07-13 12:12 UTC, ainamori commented
有り難うございます、修正しました

2023-07-13 12:36 UTC, igrep approved these changes
LGTM!
![Egg5oiHU4AAjqp9](https://github.com/iij/bootcamp/assets/227057/160a0106-0e4c-4633-9b68-9cfd542c4099)

2023-07-13 12:36 UTC, merged